# Generated by Django 5.0 on 2024-01-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_master', '0003_amssubject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_category_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('mobile', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('join_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('salary', models.PositiveIntegerField()),
                ('barcode', models.ImageField(blank=True, null=True, upload_to='barcode/')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')])),
                ('status', models.BooleanField(default=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amsdepartment')),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amsdesignation')),
                ('employee_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amsemployeecategory')),
                ('qualification_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amsqualification')),
            ],
        ),
        migrations.CreateModel(
            name='employeedesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('designation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amsdesignation')),
                ('employee_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
            ],
        ),
        migrations.CreateModel(
            name='employeedpepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amsdepartment')),
                ('employee_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('employee_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='admin_employee.adminemp')),
            ],
        ),
        migrations.CreateModel(
            name='subjectclassdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amsclass')),
                ('division_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amsdivision')),
                ('employee_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_employee.adminemp')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_master.amssubject')),
            ],
        ),
    ]
