# Generated by Django 5.0 on 2024-01-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amsemployeecategory',
            name='employee_category_area',
            field=models.IntegerField(choices=[(1, 'Accountant'), (2, 'Teacher'), (3, 'Librarian'), (4, 'Cafeteria'), (5, 'Other')]),
        ),
    ]
