# Generated by Django 5.0 on 2024-01-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_master', '0002_alter_amsemployeecategory_employee_category_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmsSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('class_name', models.ManyToManyField(to='admin_master.amsclass')),
            ],
        ),
    ]
